Sleep 2s
Type 'booky add https://overthewire.org/wargames/ -n "over the wire" -d "hacking wargames and ctfs" -t hacking,wargames,ctfs,learning,linux'
Sleep 500ms
Enter
Sleep 2s
Type "booky"
Enter
Type "/backend"
Sleep 2.5s
Backspace 7
Type "learng"
Sleep 1.5s
Backspace 6
Type "hacking"
Sleep 1.5s
Backspace 7
Sleep 1s
Enter
Sleep 500ms
Type "/boo"
Sleep 1s
Backspace 3
Sleep 500ms
Type "boot"
Sleep 1s
Enter
Sleep 2.5s
Type "q"
Sleep 1.5s

Output booky.gif
